# =================
# Antigen
# =================

# Detect OS and architecture to determine Homebrew path
if [[ "$OSTYPE" == darwin* ]]; then
    # macOS
    if [[ "$(uname -m)" == arm* ]]; then
        # Apple Silicon
        ANTIGEN_PATH="/opt/homebrew/share/antigen/antigen.zsh"
    else
        # Intel
        ANTIGEN_PATH="/usr/local/share/antigen/antigen.zsh"
    fi
else
    # Debian
    ANTIGEN_PATH="/usr/share/zsh-antigen/antigen.zsh"
fi

# Source Antigen
source $ANTIGEN_PATH

# Load oh-my-zsh library
antigen use oh-my-zsh

# Load bundles from the default repo (oh-my-zsh)
antigen bundle git
antigen bundle command-not-found

# Load bundles from external repos
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting

# Select theme
antigen theme robbyrussell

antigen apply

# =================
# Git
# =================

alias gl='glg $(git show-ref | cut -d " " -f 2 | grep -v stash$) HEAD'
alias gsw='git show --format=fuller --stat --patch'
alias gco='git checkout'
alias gs='git status --untracked-files=all'
alias gst='git stash --include-untracked --keep-index'
alias gstp='git stash pop'
alias gd='git diff -M40'
alias gdw='gd --word-diff=color --word-diff-regex="[A-z0-9_-]+"'
alias gbdw='gbd --word-diff=color --word-diff-regex="[A-z0-9_-]+"'
alias gds='gd --cached'
alias gdsw='gdw --cached'
alias grs='git reset HEAD'
alias grsp='git reset -p HEAD'
alias grsh='git reset HEAD~1'
alias ga='git add'
alias gap='git add -p'
alias gc='git commit -v'
alias gcn='git commit -n -v'
alias gca='gc --amend'
alias gcan='gcn --amend'
alias gp='git push'
alias gpt='git push -u origin $(git_current_branch)'
alias gwip='git add -A; git commit -n -m "WIP"'
alias grb='git rebase'

# helper for git aliases
function git_current_branch()
{
  git symbolic-ref --short -q HEAD
}

# =================
# Export
# =================
alias vim='nvim'
alias lg='lazygit'

export PATH=/opt/homebrew/bin:$PATH
export ANDROID_SDK_ROOT=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_SDK_ROOT/emulator
export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools
export PATH=$HOME/.local/bin:$PATH
export PATH="/opt/homebrew/opt/postgresql@16/bin:$PATH"
export EDITOR='nvim'
export XDG_CONFIG_HOME="$HOME/.config"
export RUBYOPT=-W0 # Disable ruby warnings

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

eval "$(zoxide init zsh)"
eval "$(zellij setup --generate-auto-start zsh)"
eval "$(mise activate zsh)"
eval "$(mcfly init zsh)"
